export const CREATE_NEW_BOARD = "CREATE_NEW_BOARD"
export const FETCH_BOARDS = "FETCH_BOARDS"
export const FETCH_BOARD_DETAILS = "FETCH_BOARD_DETAILS"
export const SET_ACTIVE_BOARD = "SET_ACTIVE_BOARD"

export const PENDING = "_PENDING"
export const FULFILLED = "_FULFILLED"
export const ERROR = "_ERROR"